/**
 * @description       : This class contains all generic methods
 * @author            : Siddharth Pandit
 * @group             : 
 * @last modified on  : 08-31-2020
 * @last modified by  : Siddharth Pandit
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   08-21-2020   Siddharth Pandit   Initial Version
**/
public with sharing class Utility {
    public static Boolean isFirstRun = true;
}